global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "enterprise-km-server"
    metrics_path: /metrics
    static_configs:
      - targets: ["enterprise-km-server:5056"]

  - job_name: "enterprise-km-classifier"
    metrics_path: /metrics
    static_configs:
      - targets: ["enterprise-km-classifier:5057"]

  - job_name: "open-notebook"
    static_configs:
      - targets: ["open-notebook:5055"]

  - job_name: "minio"
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ["minio:9000"]
